echo "Ping/Dig Version #0.0.3";
echo "To be used as 'custom command in Virtualmin : Webmin -> Tools -> Custom Commands': just change domain name!"
echo "";

echo "PING";
echo "";
echo "bislinks.com";
ping -c1 -4 bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";
echo "ns1.bislinks.com";
ping -c1 -4 ns1.bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";
echo "ns3.bislinks.com";
ping -c1 -4 ns3.bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";
echo "ns4.bislinks.com";
ping -c1 -4 ns4.bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";
echo "ns5.bislinks.com";
ping -c1 -4 ns5.bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";
echo "ns7.bislinks.com";
ping -c1 -4 ns7.bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";
echo "ns40.bislinks.com";
ping -c1 -4 ns40.bislinks.com | head -n1 | cut -d"(" -f2 | cut -d")" -f1;
echo "";

echo "DIG";
echo "";
echo "NS";
dig +short bislinks.com ns;
echo "";
echo "@ns1 A";
dig +short @ns1.bislinks.com bislinks.com a;
echo "";
echo "@ns3 A";
dig +short @ns3.bislinks.com bislinks.com a;
echo "";
echo "@ns4 A";
dig +short @ns4.bislinks.com bislinks.com a;
echo "";
echo "@ns5 A";
dig +short @ns5.bislinks.com bislinks.com a;
echo "";
echo "@ns7 A";
dig +short @ns7.bislinks.com bislinks.com a;
echo "";
echo "@ns40 A";
dig +short @ns40.bislinks.com bislinks.com a;
echo "";

echo "DIG SOA";
echo "";
echo "@ns1 SOA";
dig +short @ns1.bislinks.com bislinks.com soa;
echo "";
echo "@ns3 SOA";
dig +short @ns3.bislinks.com bislinks.com soa;
echo "";
echo "@ns5 SOA";
dig +short @ns5.bislinks.com bislinks.com soa;
echo "";
echo "@ns7 SOA";
dig +short @ns7.bislinks.com bislinks.com soa;
echo "";
echo "@ns40 SOA";
dig +short @ns40.bislinks.com bislinks.com soa;
echo "";
